### ISSUE TITLE
nom ERR! - module is not available to install

### ISSUE THREAD

**Issue by okkan** [SlimIO/Mib-Parser#1]
```
$ npm i @slimio/mib-parser --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@slimio%2fmib-parser - Not found
npm ERR! 404
npm ERR! 404  '@slimio/mib-parser@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by fraxken** [comment]
Hi okkan,

This project is not a package yet (just an experimentation at this state). That why there is not much work done around documentation etc.

I'm not working much around SNMP monitoring these days so i'v not planned yet to come back on the subject (my goal here was to study if there was good way to create an efficient LL1 for ASN1).

Best Regards,
Thomas
